server:
  port: 8085

viberbot:
  authToken: "4efa5ac25a67de5a-8ac2a937b00091bd-24bb6e55bcc4aef1"
  webhookUrl: "https://golets.site"
  name: "OrdersSearch"
  avatar: "https://golets-pdf.s3.eu-central-1.amazonaws.com/geek-avatar.jpg"
  seleniumBotUrl: "http://selenium-bot:8083"

logging.level.root: INFO
logging.level.com.viber.bot: DEBUG
logging.level.com.gargoylesoftware: INFO
