version: "2.0"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl-bundle.crt:/etc/ssl/ssl-bundle.crt
      - ./golets_site.pem:/etc/ssl/golets_site.pem
      - ./index.html:/etc/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
    networks:
      order-search-net:

  viber-bot:
    container_name: viber-bot
    image: 415800032746.dkr.ecr.us-west-2.amazonaws.com/viber-bot:0.1.1-SNAPSHOT
    ports:
      - "8085:8085"
    networks:
      order-search-net:
    depends_on:
      - nginx

  selenium-bot:
    container_name: selenium-bot
    image: 415800032746.dkr.ecr.us-west-2.amazonaws.com/selenium-bot:1.0-SNAPSHOT
    ports:
      - "8083:8083"
    networks:
      order-search-net:
    depends_on:
      - selenium-chrome

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/standalone-chrome
    ports:
      - "4445:4444"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      order-search-net:

networks:
  order-search-net:
    driver: bridge
